updated CF template for AMI creation, fixes

diff --git a/spotty/data/create_ami.yaml b/spotty/data/create_ami.yaml
--- a/spotty/data/create_ami.yaml
+++ b/spotty/data/create_ami.yaml
@@ -1,4 +1,6 @@
 Description: Spotty NVIDIA Docker AMI
+Metadata:
+  Version: 1.0.1
 Parameters:
   InstanceType:
     Description: Instance type to launch EC2 Spot instance
@@ -9,11 +11,6 @@ Parameters:
   KeyName:
     Description: Key name to get an access o the instance
     Type: AWS::EC2::KeyPair::KeyName
-  IgnoreCreateAMIFunction:
-    Description: Run an instance without creating an AMI
-    Type: String
-    Default: 'false'
-    AllowedValues: ['true', 'false']
 Resources:
   FindBaseAMI:
     Type: Custom::AMI
@@ -27,8 +24,7 @@ Resources:
       Role: !GetAtt FindBaseAMILambdaExecutionRole.Arn
       Code:
         ZipFile: !Sub |
-          var aws=require("aws-sdk");var response=require('cfn-response');exports.handler=function(event,context){console.log("request received:\n"+JSON.stringify(event));var physicalId=event.PhysicalResourceId;function success(data){data=data||{}
-          console.log('SUCCESS:\n',data);return response.send(event,context,response.SUCCESS,data,physicalId)}
+          var aws=require("aws-sdk");var response=require('cfn-response');exports.handler=function(event,context){console.log("request received:\n"+JSON.stringify(event));var physicalId=event.PhysicalResourceId;function success(data){data=data||{};console.log('SUCCESS:\n',data);return response.send(event,context,response.SUCCESS,data,physicalId)}
           function failed(err){console.log('FAILED:\n',err);return response.send(event,context,response.FAILED,err,physicalId)}
           if(event.RequestType=='Delete'){console.log('Delete request is ignored');return success()}
           var ec2=new aws.EC2({region:event.ResourceProperties.Region});ec2.describeImages({Filters:[{Name:"name",Values:['ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64*']}],Owners:['099720109477']}).promise().then((data)=>{console.log('Number of found images: ',data.Images.length);var images=data.Images;images.sort(function(x,y){return y.Name.localeCompare(x.Name)});var amiId=!1;for(var j=0;j<images.length;j++){if(isBeta(images[j].Name))continue;amiId=images[j].ImageId;break}
@@ -65,12 +61,13 @@ Resources:
             Action:
             - 'ec2:DescribeImages'
             Resource: '*'
-  FindBaseAMIFunctionRetention:
+  DeleteAMIFunctionRetention:
     Type: Custom::LogsRetention
     DependsOn: FindBaseAMI
     Properties:
       ServiceToken: !GetAtt SetLogsRetentionFunction.Arn
       LogGroupName: !Join ['', ['/aws/lambda/', !Ref FindBaseAMIFunction]]
+      RetentionInDays: 1
 
   SpotInstance:
     Type: AWS::EC2::Instance
@@ -88,7 +85,7 @@ Resources:
         KeyName: !Ref KeyName
         EbsOptimized: 'false'
         IamInstanceProfile:
-          Arn: !GetAtt LogRoleInstanceProfile.Arn
+          Arn: !GetAtt InstanceProfile.Arn
         InstanceInitiatedShutdownBehavior: terminate
         InstanceMarketOptions:
           MarketType: spot
@@ -118,7 +115,7 @@ Resources:
               --region ${AWS::Region} \
               -c cwlogs
 
-            # install Docker and goofys
+            # install NVIDIA Docker
             /usr/local/bin/cfn-init \
               --stack ${AWS::StackName} \
               --resource SpotInstanceLaunchTemplate \
@@ -126,22 +123,54 @@ Resources:
               -c init \
               -v
 
-            # send signal to create an AMI
+            INIT_EXIT_CODE=$?
+
+            # send signal that the instance is ready
             /usr/local/bin/cfn-signal \
-              -e $? \
+              -e $INIT_EXIT_CODE \
               --stack ${AWS::StackName} \
               --region ${AWS::Region} \
               --resource InstanceReadyWaitCondition
+
+            if [[ $INIT_EXIT_CODE -ne 0 ]] ; then
+              exit $INIT_EXIT_CODE
+            fi
+
+            # create the AMI
+            /usr/local/bin/cfn-init \
+              --stack ${AWS::StackName} \
+              --resource SpotInstanceLaunchTemplate \
+              --region ${AWS::Region} \
+              -c ami \
+              -v
+
+            AMI_EXIT_CODE=$?
+
+            # send signal that the AMI is created
+            /usr/local/bin/cfn-signal \
+              -e $AMI_EXIT_CODE \
+              --stack ${AWS::StackName} \
+              --region ${AWS::Region} \
+              --resource AMICreatedWaitCondition
+
+            if [[ $AMI_EXIT_CODE -ne 0 ]] ; then
+              exit $AMI_EXIT_CODE
+            fi
+
+            # shutdown the instance
+            shutdown -h now
     Metadata:
       'AWS::CloudFormation::Init':
         configSets:
           init:
             - init_config
+          ami:
+            - ami_config
           cwlogs:
             - cwlogs_config
         init_config:
           files:
-            /root/init.sh:
+            /tmp/scripts/init.sh:
               content: !Sub |
                 # install Docker
                 apt-get update
@@ -178,7 +207,30 @@ Resources:
               group: root
           commands:
             run_init:
-              command: "/bin/bash -xe /root/init.sh"
+              command: '/bin/bash -xe /tmp/scripts/init.sh'
+        ami_config:
+          files:
+            /tmp/scripts/create_ami.sh:
+              content: !Sub |
+                # install AWS CLI
+                apt-get install -y awscli
+                aws configure set default.region ${AWS::Region}
+
+                # install jq
+                apt-get install -y jq
+
+                # create AMI
+                INSTANCE_ID=`curl http://169.254.169.254/latest/meta-data/instance-id`
+                IMAGE_ID=`aws ec2 create-image --instance-id $INSTANCE_ID --name "${ImageName}" --no-reboot | jq -r '.ImageId'`
+                aws ec2 create-tags --resources $IMAGE_ID \
+                  --tags Key=spotty:stack-id,Value=${AWS::StackId} "Key=Name,Value=NVIDIA Docker"
+                aws ec2 wait image-available --image-ids $IMAGE_ID
+              mode: '000755'
+              owner: root
+              group: root
+          commands:
+            create_ami:
+              command: '/bin/bash -xe /tmp/scripts/create_ami.sh'
         cwlogs_config:
           files:
             /tmp/cwlogs/logs.conf:
@@ -188,13 +240,13 @@ Resources:
 
                 [/var/log/cloud-init-output.log]
                 file = /var/log/cloud-init-output.log
-                log_group_name = ${SpotInstanceLogGroup}
+                log_group_name = ${InstanceLogGroup}
                 log_stream_name = {instance_id}/cloud-init-output.log
                 datetime_format = %d/%b/%Y:%H:%M:%S
 
                 [/var/log/cfn-init.log]
                 file = /var/log/cfn-init.log
-                log_group_name = ${SpotInstanceLogGroup}
+                log_group_name = ${InstanceLogGroup}
                 log_stream_name = {instance_id}/cfn-init.log
                 datetime_format = %d/%b/%Y:%H:%M:%S
               mode: '000400'
@@ -212,10 +264,10 @@ Resources:
           commands:
             run_cw_agent:
               command: '/bin/bash -xe /tmp/cwlogs/run.sh'
-  SpotInstanceLogGroup:
+
+  InstanceLogGroup:
     Type: AWS::Logs::LogGroup
-    Properties:
-      RetentionInDays: 7
+
   LogRole:
     Type: AWS::IAM::Role
     Properties:
@@ -230,7 +282,7 @@ Resources:
           - sts:AssumeRole
       Path: '/'
       Policies:
-      - PolicyName: LogRolePolicy
+      - PolicyName: LogsPolicy
         PolicyDocument:
           Version: '2012-10-17'
           Statement:
@@ -242,7 +294,17 @@ Resources:
             Resource:
             - arn:aws:logs:*:*:*
             - arn:aws:s3:::*
-  LogRoleInstanceProfile:
+      - PolicyName: AMICreationPolicy
+        PolicyDocument:
+          Version: '2012-10-17'
+          Statement:
+          - Effect: Allow
+            Action:
+            - 'ec2:DescribeImages'
+            - 'ec2:CreateImage'
+            - 'ec2:CreateTags'
+            Resource: ['*']
+  InstanceProfile:
     Type: AWS::IAM::InstanceProfile
     Properties:
       Path: '/'
@@ -255,38 +317,35 @@ Resources:
     CreationPolicy:
       ResourceSignal:
         Timeout: PT20M
-  CreateAMI:
+
+  AMICreatedWaitCondition:
+    Type: AWS::CloudFormation::WaitCondition
+    DependsOn: SpotInstance
+    CreationPolicy:
+      ResourceSignal:
+        Timeout: PT30M
+
+  DeleteAMI:
     Type: Custom::AMI
-    DependsOn: InstanceReadyWaitCondition
+    DependsOn: AMICreatedWaitCondition
     Properties:
-      ServiceToken: !GetAtt CreateAMIFunction.Arn
-      InstanceId: !Ref SpotInstance
-      ImageName: !Ref ImageName
-      IgnoreFunction: !Ref IgnoreCreateAMIFunction
-  CreateAMIFunction:
+      ServiceToken: !GetAtt DeleteAMIFunction.Arn
+  DeleteAMIFunction:
     Type: AWS::Lambda::Function
     Properties:
       Handler: index.handler
-      Role: !GetAtt CreateAMILambdaExecutionRole.Arn
+      Role: !GetAtt DeleteAMILambdaExecutionRole.Arn
       Code:
         ZipFile: !Sub |
-          var AWS=require('aws-sdk');var response=require('cfn-response');exports.handler=function(event,context){console.log("Request received:\n",JSON.stringify(event));var physicalId=event.PhysicalResourceId;function success(data){data=data||{}
-          console.log('SUCCESS:\n',data);return response.send(event,context,response.SUCCESS,data,physicalId)}
+          var aws=require('aws-sdk');var response=require('cfn-response');exports.handler=function(event,context){console.log('Request received:\n',JSON.stringify(event));var physicalId=event.PhysicalResourceId;function success(data){data=data||{};console.log('SUCCESS:\n',data);return response.send(event,context,response.SUCCESS,data,physicalId)}
           function failed(err){console.log('FAILED:\n',err);return response.send(event,context,response.FAILED,err,physicalId)}
-          if(event.ResourceProperties.IgnoreFunction=='true'){console.log('AMI not created (the function is ignored)');return success()}
-          var ec2=new AWS.EC2({region:event.ResourceProperties.Region});if(event.RequestType=='Create'||event.RequestType=='Update'){var instanceId=event.ResourceProperties.InstanceId;if(!instanceId){return failed('InstanceId required')}
-          var imageName=event.ResourceProperties.ImageName;if(!imageName){return failed('ImageName required')}
-          ec2.createImage({InstanceId:instanceId,Name:imageName}).promise().then((data)=>{console.log('Creating image:\n',JSON.stringify(data));physicalId=data.ImageId;var tagsPromise=ec2.createTags({Resources:[data.ImageId],Tags:[{Key:'spotty:stack-id',Value:event.StackId}]}).promise()
-          var imageAvailablePromise=ec2.waitFor('imageAvailable',{ImageIds:[data.ImageId]}).promise()
-          return Promise.all([tagsPromise,imageAvailablePromise])}).then((data)=>{console.log('Image tagged:\n',JSON.stringify(data[0]));console.log('Image available:\n',JSON.stringify(data[1]));console.log('Terminating the instance...');return ec2.terminateInstances({InstanceIds:[instanceId]}).promise()}).then((data)=>{console.log('"terminateInstances" Response:\n',JSON.stringify(data));success()}).catch((err)=>failed(err))}else if(event.RequestType=='Delete'){if(!physicalId){console.log('AMI ID not specified')
-          return success()}else if(physicalId.indexOf('ami-')!==0){console.log('Physical ID is not an AMI ID')
-          return success()}
-          console.log('Searching AMI with ID='+physicalId);ec2.describeImages({ImageIds:[physicalId]}).promise().then((data)=>{if(!data.Images.length){throw new Error('No images found')}
-          console.log('"describeImages" response:\n',data);return ec2.deregisterImage({ImageId:physicalId}).promise()}).then((data)=>{console.log('Image deregistered:\n',data);return ec2.describeSnapshots({Filters:[{Name:'description',Values:['*'+physicalId+'*']}]}).promise()}).then((data)=>{console.log('"describeSnapshots" response:\n',data);if(!data.Snapshots.length){throw new Error('No snapshots found')}
+          var ec2=new aws.EC2({region:event.ResourceProperties.Region});if(event.RequestType=='Create'||event.RequestType=='Update'){ec2.describeImages({Filters:[{Name:'tag:spotty:stack-id',Values:[event.StackId]}]}).promise().then((data)=>{if(!data.Images.length){throw new Error('No images found')}
+          console.log('"describeImages" response:\n',data);physicalId=data.Images[0].ImageId;success()}).catch((err)=>failed(err))}else{var imageId=physicalId;console.log('Searching AMI with ID='+imageId);ec2.describeImages({ImageIds:[imageId]}).promise().then((data)=>{if(!data.Images.length){throw new Error('No images found')}
+          console.log('"describeImages" response:\n',data);return ec2.deregisterImage({ImageId:imageId}).promise()}).then((data)=>{console.log('Image deregistered:\n',data);return ec2.describeSnapshots({Filters:[{Name:'description',Values:['*'+imageId+'*']}]}).promise()}).then((data)=>{console.log('"describeSnapshots" response:\n',data);if(!data.Snapshots.length){throw new Error('No snapshots found')}
           return ec2.deleteSnapshot({SnapshotId:data.Snapshots[0].SnapshotId}).promise()}).then((data)=>{console.log('Snapshot deleted:\n',data);success()}).catch((err)=>failed(err))}}
       Runtime: nodejs4.3
-      Timeout: 300
-  CreateAMILambdaExecutionRole:
+      Timeout: 60
+  DeleteAMILambdaExecutionRole:
     Type: AWS::IAM::Role
     Properties:
       AssumeRolePolicyDocument:
@@ -309,23 +368,20 @@ Resources:
           Statement:
             - Effect: Allow
               Action:
-              - 'ec2:DescribeInstances'
               - 'ec2:DescribeImages'
-              - 'ec2:CreateImage'
-              - 'ec2:DeregisterImage'
               - 'ec2:DescribeSnapshots'
+              - 'ec2:DeregisterImage'
               - 'ec2:DeleteSnapshot'
-              - 'ec2:TerminateInstances'
-              - 'ec2:CreateTags'
               Resource: ['*']
-  CreateAMIFunctionRetention:
+  DeleteAMIFunctionRetention:
     Type: Custom::LogsRetention
-    DependsOn: CreateAMI
+    DependsOn: DeleteAMI
     Properties:
       ServiceToken: !GetAtt SetLogsRetentionFunction.Arn
-      LogGroupName: !Join ['', ['/aws/lambda/', !Ref CreateAMIFunction]]
+      LogGroupName: !Join ['', ['/aws/lambda/', !Ref DeleteAMIFunction]]
+      RetentionInDays: 1
 
-  # function to set logs retention for a log group to 1 day (for lambdas by default they never expire)
+  # function to change a log group retention (for lambdas by default they never expire)
   SetLogsRetentionFunction:
     Type: AWS::Lambda::Function
     Properties:
@@ -334,13 +390,14 @@ Resources:
       Runtime: nodejs4.3
       Timeout: 30
       Code:
-        ZipFile: !Sub |
+        ZipFile: |
           var aws=require("aws-sdk");var response=require('cfn-response');exports.handler=function(event,context){console.log("request received:\n"+JSON.stringify(event));var physicalId=event.PhysicalResourceId;function success(data){data=data||{}
           console.log('SUCCESS:\n',data);return response.send(event,context,response.SUCCESS,data,physicalId)}
           function failed(err){console.log('FAILED:\n',err);return response.send(event,context,response.FAILED,err,physicalId)}
           if(event.RequestType!=='Create'){console.log('Non-create request is ignored');return success()}
           var logGroupName=event.ResourceProperties.LogGroupName;if(!logGroupName){return failed('LogGroupName required')}
-          var cloudwatchlogs=new aws.CloudWatchLogs();cloudwatchlogs.putRetentionPolicy({logGroupName:logGroupName,retentionInDays:1}).promise().then((data)=>{console.log('"putRetentionPolicy" Response:\n',JSON.stringify(data));success()}).catch((err)=>failed(err))}
+          var retentionInDays=event.ResourceProperties.RetentionInDays;if(!retentionInDays){return failed('RetentionInDays required')}
+          var cloudwatchlogs=new aws.CloudWatchLogs();cloudwatchlogs.putRetentionPolicy({logGroupName:logGroupName,retentionInDays:retentionInDays}).promise().then((data)=>{console.log('"putRetentionPolicy" Response:\n',JSON.stringify(data));success()}).catch((err)=>failed(err))}
   SetLogsRetentionLambdaExecutionRole:
     Type: AWS::IAM::Role
     Properties:
@@ -372,6 +429,7 @@ Resources:
     Properties:
       ServiceToken: !GetAtt SetLogsRetentionFunction.Arn
       LogGroupName: !Join ['', ['/aws/lambda/', !Ref SetLogsRetentionFunction]]
+      RetentionInDays: 1
 
 Outputs:
   BaseAMI:
@@ -379,4 +437,7 @@ Outputs:
     Value: !Ref FindBaseAMI
   NewAMI:
     Description: Created AMI ID
-    Value: !Ref CreateAMI
+    Value: !Ref DeleteAMI
+  InstanceLogGroupName:
+    Description: CloudWatch log group name for the instance
+    Value: !Ref InstanceLogGroup
