attaching multiple volumes to the instance

diff --git a/spotty/data/run_container.yaml b/spotty/data/run_container.yaml
--- a/spotty/data/run_container.yaml
+++ b/spotty/data/run_container.yaml
@@ -15,8 +15,8 @@ Parameters:
   RootVolumeSize:
     Description: Root volume size
     Type: String
-  VolumeMountDirectory:
-    Description: Directory where the volume should be mounted
+  VolumeMountDirectories:
+    Description: Directories where the volumes should be mounted (bash array)
     Type: String
     Default: ''
   DockerDataRootDirectory:
@@ -51,6 +51,7 @@ Parameters:
 Resources:
   SpotInstance:
     Type: AWS::EC2::Instance
+    DependsOn: CreateSnapshots
     Properties:
       LaunchTemplate:
         LaunchTemplateId: !Ref SpotInstanceLaunchTemplate
@@ -90,21 +91,6 @@ Resources:
             curl https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz | tar xz -C aws-cfn-bootstrap-latest --strip-components 1
             easy_install aws-cfn-bootstrap-latest
 
-            # install AWS CLI
-            apt-get install -y awscli
-            aws configure set default.region ${AWS::Region}
-
-            # install jq
-            apt-get install -y jq
-
-            # create directory for Docker scripts
-            mkdir -p /tmp/docker
-            chmod 777 /tmp/docker
-
-            # create directory for "spotty run" logs
-            mkdir -p /var/log/spotty-run
-            chmod 777 /var/log/spotty-run
-
             # install CloudWatch agent
             /usr/local/bin/cfn-init \
               --stack ${AWS::StackName} \
@@ -113,22 +99,30 @@ Resources:
               -c cwlogs \
               -v
 
+            # prepare the instance
             /usr/local/bin/cfn-init \
               --stack ${AWS::StackName} \
               --resource SpotInstanceLaunchTemplate \
               --region ${AWS::Region} \
-              -c cfn_hup \
+              -c init \
+              -v
+
+            # sync the project and start Docker conatainer
+            /usr/local/bin/cfn-init \
+              --stack ${AWS::StackName} \
+              --resource SpotInstanceLaunchTemplate \
+              --region ${AWS::Region} \
+              -c start_docker \
               -v
     Metadata:
       'AWS::CloudFormation::Init':
         configSets:
           cwlogs:
             - cwlogs_config
-          cfn_hup:
-            - cfn_hup_config
+          init:
+            - prepare_instance_config
+            - mount_volumes_config
           start_docker:
-            - stop_cfn_hup_config
-            - mount_volume_config
             - sync_project_config
             - docker_container_config
         cwlogs_config:
@@ -181,59 +175,49 @@ Resources:
           commands:
             run_cw_agent:
               command: '/bin/bash -xe /tmp/cwlogs/run.sh'
-        cfn_hup_config:
+        prepare_instance_config:
           files:
-            /tmp/scripts/start_docker.sh:
+            /tmp/scripts/prepare_instance.sh:
               owner: root
               group: root
               mode: '000400'
               content: !Sub |
-                /usr/local/bin/cfn-init --stack ${AWS::StackName} --resource SpotInstanceLaunchTemplate --region ${AWS::Region} -c start_docker -v
-                /usr/local/bin/cfn-signal -e $? --stack ${AWS::StackName} --region ${AWS::Region} --resource DockerReadyWaitCondition
-            /etc/cfn/cfn-hup.conf:
-              owner: root
-              group: root
-              mode: '000400'
-              content: !Sub |
-                [main]
-                stack=${AWS::StackId}
-                region=${AWS::Region}
-                interval=1
-                verbose=true
-            /etc/cfn/hooks.d/cfn-volume-attached.conf:
-              owner: root
-              group: root
-              mode: '000400'
-              content: !Sub |
-                [cfn-volume-attached-hook]
-                triggers=post.add
-                path=Resources.VolumeAttachment1.PhysicalResourceId
-                action=/bin/bash -x /tmp/scripts/start_docker.sh
-                runas=root
-          commands:
-            run_init:
-              command: '/usr/local/bin/cfn-hup -v'
-        stop_cfn_hup_config:
-          commands:
-            stop_cfn_hup:
-              command: 'kill -9 `pgrep cfn-hup`'
-        mount_volume_config:
-          files:
-            /tmp/scripts/mount_volume.sh:
-              owner: root
-              group: root
-              mode: '000400'
-              content: !Sub |
-                if [ -n "${VolumeMountDirectory}" ]; then
-                  DEVICE=/dev/xvdb
-                  blkid -o value -s TYPE $DEVICE || mkfs -t ext4 $DEVICE
-                  mkdir -p ${VolumeMountDirectory}
-                  mount $DEVICE ${VolumeMountDirectory}
-                  chown -R ubuntu:ubuntu ${VolumeMountDirectory}
-                fi
+                # install AWS CLI
+                apt-get install -y awscli
+                aws configure set default.region ${AWS::Region}
+
+                # install jq
+                apt-get install -y jq
+
+                # create directory for "spotty run" logs
+                mkdir -p /var/log/spotty-run
+                chmod 777 /var/log/spotty-run
           commands:
             mount_volume:
-              command: '/bin/bash -xe /tmp/scripts/mount_volume.sh'
+              command: '/bin/bash -xe /tmp/scripts/prepare_instance.sh'
+        mount_volumes_config:
+          files:
+            /tmp/scripts/mount_volumes.sh:
+              owner: root
+              group: root
+              mode: '000400'
+              content: !Sub |
+                DEVICE_LETTERS=(f g h i j k l m n o p)
+                MOUNT_DIRS=(${VolumeMountDirectories})
+
+                for i in ${!!MOUNT_DIRS[*]}
+                do
+                  DEVICE=/dev/xvd${!DEVICE_LETTERS[$i]}
+                  MOUNT_DIR=${!MOUNT_DIRS[$i]}
+
+                  blkid -o value -s TYPE $DEVICE || mkfs -t ext4 $DEVICE
+                  mkdir -p $MOUNT_DIR
+                  mount $DEVICE $MOUNT_DIR
+                  chown -R ubuntu:ubuntu $MOUNT_DIR
+                done
+          commands:
+            mount_volumes:
+              command: '/bin/bash -xe /tmp/scripts/mount_volumes.sh'
         sync_project_config:
           files:
             /tmp/scripts/sync_project.sh:
@@ -273,18 +257,24 @@ Resources:
                 fi
 
                 if [ -n "$DOCKER_IMAGE" ]; then
-                  VOLUME_PARAM=""
-                  if [ -n "${VolumeMountDirectory}" ]; then
-                    VOLUME_PARAM="-v ${VolumeMountDirectory}:${VolumeMountDirectory}"
-                  fi
+                  MOUNT_DIRS=(${VolumeMountDirectories})
+                  VOLUME_PARAMS=""
+                  for mount_dir in ${!MOUNT_DIRS[*]}
+                  do
+                    VOLUME_PARAMS="VOLUME_PARAMS -v $mount_dir:$mount_dir"
+                  done
 
                   NVIDIA_RUNTIME=""
                   if [ "${DockerNvidiaRuntime}" == "true" ]; then
                     NVIDIA_RUNTIME="--runtime=nvidia"
                   fi
 
+                  # create directory for Docker scripts
+                  mkdir -p /tmp/docker
+                  chmod 777 /tmp/docker
+
                   # run docker container
-                  docker run $NVIDIA_RUNTIME --net=host -td $VOLUME_PARAM \
+                  docker run $NVIDIA_RUNTIME --net=host -td $VOLUME_PARAMS \
                     -v /root/.aws:/root/.aws -v /tmp/docker:/tmp/docker --name spotty $DOCKER_IMAGE /bin/sh
 
                   WORKING_DIR=""
@@ -382,42 +372,31 @@ Resources:
         FromPort: 22
         ToPort: 22
 
-  Volume1:
-    Type: AWS::EC2::Volume
-    DeletionPolicy: Snapshot
+  CreateSnapshots:
+    Type: Custom::SnapshotCreation
     Properties:
-      AvailabilityZone: !GetAtt SpotInstance.AvailabilityZone
-  VolumeAttachment1:
-    Type: AWS::EC2::VolumeAttachment
-    Properties:
-      Device: /dev/sda2
-      InstanceId: !Ref SpotInstance
-      VolumeId: !Ref Volume1
-
-  # function to terminate the instance before detaching the volume
-  # (otherwise the volume will be in busy state, because it's mounted to the instance)
-  TerminateInstance:
-    Type: Custom::InstanceTermination
-    DependsOn: VolumeAttachment1
-    Properties:
-      ServiceToken: !GetAtt TerminateInstanceFunction.Arn
-      InstanceId: !Ref SpotInstance
-  TerminateInstanceFunction:
+      ServiceToken: !GetAtt CreateSnapshotsFunction.Arn
+      Devices: {}
+  CreateSnapshotsFunction:
     Type: AWS::Lambda::Function
     Properties:
       Handler: index.handler
-      Role: !GetAtt TerminateInstanceLambdaExecutionRole.Arn
+      Role: !GetAtt CreateSnapshotsLambdaExecutionRole.Arn
       Runtime: nodejs4.3
       Timeout: 30
       Code:
-        ZipFile: !Sub |
-          var aws=require("aws-sdk");var response=require('cfn-response');exports.handler=function(event,context){console.log("request received:\n"+JSON.stringify(event));var physicalId=event.PhysicalResourceId;function success(data){data=data||{}
-          console.log('SUCCESS:\n',data);return response.send(event,context,response.SUCCESS,data,physicalId)}
+        ZipFile: |
+          var aws=require('aws-sdk');var response=require('cfn-response');exports.handler=function(event,context){console.log('Request received:\n'+JSON.stringify(event));var physicalId=event.PhysicalResourceId;function success(data){data=data||{};console.log('SUCCESS:\n',data);return response.send(event,context,response.SUCCESS,data,physicalId)}
           function failed(err){console.log('FAILED:\n',err);return response.send(event,context,response.FAILED,err,physicalId)}
           if(event.RequestType!=='Delete'){console.log('Non-delete request is ignored');return success()}
-          var instanceId=event.ResourceProperties.InstanceId;if(!instanceId){return failed('InstanceId required')}
-          var ec2=new aws.EC2({region:event.ResourceProperties.Region});ec2.terminateInstances({InstanceIds:[instanceId]}).promise().then((data)=>{console.log('"terminateInstances" Response:\n',JSON.stringify(data));success()}).catch((err)=>failed(err))}
-  TerminateInstanceLambdaExecutionRole:
+          var devices=event.ResourceProperties.Devices;if(!devices){console.log('Devices not specified');return success()}
+          var ec2=new aws.EC2({region:event.ResourceProperties.Region});ec2.describeVolumes({Filters:[{Name:'tag:aws:cloudformation:stack-id',Values:[event.StackId]},{Name:'attachment.delete-on-termination',Values:['false']}]}).promise().then((data)=>{console.log('"describeVolumes" response:\n',JSON.stringify(data));var volumePromises=[];for(var i=0;i<data.Volumes.length;i++){var volume=data.Volumes[i],deviceName=volume.Attachments[0].Device;if(!(deviceName in devices)){throw 'Device "'+deviceName+'" not found'}
+          var mode=devices[deviceName].mode,snapshotName=devices[deviceName].snapshotName,origSnapshotId=devices[deviceName].snapshotId;var snapshotPromise=ec2.createSnapshot({VolumeId:volume.VolumeId}).promise().then((data)=>{console.log('"createSnapshot" response:\n',JSON.stringify(data));return ec2.waitFor('snapshotCompleted',{SnapshotIds:[data.SnapshotId]}).promise()});var origSnapshotPromise=snapshotPromise.then((data)=>{console.log('"snapshotCompleted" response:\n',JSON.stringify(data));if(data.Snapshots[0].State!='completed'){throw 'Snapshot is not completed'}
+          var describeSnapshotsPromise;if(origSnapshotId){describeSnapshotsPromise=ec2.describeSnapshots({Filters:[{Name:'snapshot-id',Values:[origSnapshotId]}]}).promise().then((data)=>{console.log('"describeSnapshots" response:\n',JSON.stringify(data));var updateSnapshotPromise;if(data.Snapshots.length){switch(mode){case 'update':updateSnapshotPromise=ec2.deleteSnapshot({SnapshotId:origSnapshotId}).promise();break;case 'create':updateSnapshotPromise=ec2.createTags({Resources:[origSnapshotId],Tags:[{Key:'Name',Value:snapshotName+'-'+Math.floor(Date.now()/60000)}],}).promise();break;default:throw 'Mode "'+mode+'" not supported'}}else{console.log('Original snapshot not found')}
+          return updateSnapshotPromise})}else{console.log('Original snapshot not specified')}
+          return describeSnapshotsPromise});var volumePromise=Promise.all([snapshotPromise,origSnapshotPromise]).then(function(data){var snapshotsResp=data[0];return ec2.createTags({Resources:[snapshotsResp.Snapshots[0].SnapshotId],Tags:[{Key:'Name',Value:snapshotName}]}).promise()}).then((data)=>{ec2.deleteVolume({VolumeId:volume.VolumeId})});volumePromises.push(volumePromise)}
+          return Promise.all(volumePromises)}).then((data)=>{console.log('"deleteVolume" responses:\n',JSON.stringify(data));success()}).catch((err)=>failed(err))}
+  CreateSnapshotsLambdaExecutionRole:
     Type: AWS::IAM::Role
     Properties:
       AssumeRolePolicyDocument:
@@ -440,70 +419,19 @@ Resources:
           Statement:
             - Effect: Allow
               Action:
-              - 'ec2:TerminateInstances'
-              Resource: ['*']
-  TerminateInstanceFunctionRetention:
-    Type: Custom::LogsRetention
-    DependsOn: TerminateInstance
-    Properties:
-      ServiceToken: !GetAtt SetLogsRetentionFunction.Arn
-      LogGroupName: !Join ['', ['/aws/lambda/', !Ref TerminateInstanceFunction]]
-      RetentionInDays: 1
-
-  # function to delete the snapshot which was used to create the volume
-  DeleteSnapshot:
-    Type: Custom::SnapshotDeletion
-    DependsOn: Volume1
-    Properties:
-      ServiceToken: !GetAtt DeleteSnapshotFunction.Arn
-      SnapshotId: ''
-  DeleteSnapshotFunction:
-    Type: AWS::Lambda::Function
-    Properties:
-      Handler: index.handler
-      Role: !GetAtt DeleteSnapshotLambdaExecutionRole.Arn
-      Runtime: nodejs4.3
-      Timeout: 30
-      Code:
-        ZipFile: !Sub |
-          var aws=require('aws-sdk');var response=require('cfn-response');exports.handler=function(event,context){console.log('Request received:\n'+JSON.stringify(event));var physicalId=event.PhysicalResourceId;function success(data){data=data||{}
-          console.log('SUCCESS:\n',data);return response.send(event,context,response.SUCCESS,data,physicalId)}
-          function failed(err){console.log('FAILED:\n',err);return response.send(event,context,response.FAILED,err,physicalId)}
-          if(event.RequestType!=='Delete'){console.log('Non-delete request is ignored');return success()}
-          var snapshotId=event.ResourceProperties.SnapshotId;if(!snapshotId){console.log('Nothing to delete');return success()}
-          var ec2=new aws.EC2({region:event.ResourceProperties.Region});ec2.describeSnapshots({Filters:[{Name:'snapshot-id',Values:[snapshotId]}]}).promise().then((data)=>{console.log('"describeSnapshots" response:\n',JSON.stringify(data));if(data.Snapshots.length){ec2.deleteSnapshot({SnapshotId:snapshotId}).promise().then((data)=>{console.log('"deleteSnapshot" response:\n',JSON.stringify(data));success()}).catch((err)=>failed(err))}else{console.log('Snapshot not found');success()}}).catch((err)=>failed(err))}
-  DeleteSnapshotLambdaExecutionRole:
-    Type: AWS::IAM::Role
-    Properties:
-      AssumeRolePolicyDocument:
-        Version: '2012-10-17'
-        Statement:
-        - Effect: Allow
-          Principal:
-            Service:
-              - lambda.amazonaws.com
-          Action:
-            - 'sts:AssumeRole'
-      Path: /
-      ManagedPolicyArns:
-      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
-      - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
-      Policies:
-      - PolicyName: EC2Policy
-        PolicyDocument:
-          Version: '2012-10-17'
-          Statement:
-            - Effect: Allow
-              Action:
+              - 'ec2:DescribeVolumes'
+              - 'ec2:DeleteVolume'
               - 'ec2:DescribeSnapshots'
+              - 'ec2:CreateSnapshot'
               - 'ec2:DeleteSnapshot'
+              - 'ec2:CreateTags'
               Resource: ['*']
-  DeleteSnapshotFunctionRetention:
+  CreateSnapshotsFunctionRetention:
     Type: Custom::LogsRetention
-    DependsOn: DeleteSnapshot
+    DependsOn: CreateSnapshots
     Properties:
       ServiceToken: !GetAtt SetLogsRetentionFunction.Arn
-      LogGroupName: !Join ['', ['/aws/lambda/', !Ref DeleteSnapshotFunction]]
+      LogGroupName: !Join ['', ['/aws/lambda/', !Ref CreateSnapshotsFunction]]
       RetentionInDays: 1
 
   # function to set logs retention for a log group to 1 day (for lambdas by default they never expire)
@@ -515,7 +443,7 @@ Resources:
       Runtime: nodejs4.3
       Timeout: 30
       Code:
-        ZipFile: !Sub |
+        ZipFile: |
           var aws=require("aws-sdk");var response=require('cfn-response');exports.handler=function(event,context){console.log("request received:\n"+JSON.stringify(event));var physicalId=event.PhysicalResourceId;function success(data){data=data||{}
           console.log('SUCCESS:\n',data);return response.send(event,context,response.SUCCESS,data,physicalId)}
           function failed(err){console.log('FAILED:\n',err);return response.send(event,context,response.FAILED,err,physicalId)}
@@ -558,7 +486,7 @@ Resources:
 
   DockerReadyWaitCondition:
     Type: AWS::CloudFormation::WaitCondition
-    DependsOn: VolumeAttachment1
+    DependsOn: SpotInstance
     CreationPolicy:
       ResourceSignal:
         Timeout: PT10M
